name: Docker Image CD

on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4
    
    - name: Configure AWS  credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to ECR 
      run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u4b2j5h1
    
    - name: Build, tag, and push the Docker image
      run: |
        docker build . -t 20091409/continuous_php_image
        docker tag 20091409/continuous_php_image:latest public.ecr.aws/u4b2j5h1/20091409/continuous_php_image:latest
        docker push public.ecr.aws/u4b2j5h1/20091409/continuous_php_image:latest